#!/bin/bash
set -e -u -x
cd "$(dirname "$0")"
sudo cp dotnet-s390x-daily@.service dotnet-s390x-daily@.timer /etc/systemd/system/
sudo systemctl daemon-reload
sudo systemctl enable --now dotnet-s390x-daily@"$USER".timer
