#!/bin/bash
set -e -u -x

BASEDIR=$(pwd)
NUGET="mono ${BASEDIR}/nuget.exe"
PACKAGESDIR=${BASEDIR}/local-packages

function update_nuget_config {
    gawk -f - -i inplace NuGet.config <<EOF
    { print }
    /<packageSources>/ { Src = 1 }
    /<\/packageSources>/ { Src = 0 }
    /<clear \/>/ { if (Src) print "    <add key=\"local\" value=\"${PACKAGESDIR}\" />" }
EOF
}

function install_host_sdk {
    # Already installed?
    root=$1/.dotnet
    if [ -d "$root" ]; then return; fi

    # Installer available?
    version=$(jq -r .tools.dotnet "$1/global.json")
    cache_dir=$HOME/.dotnet
    tgz_name=dotnet-sdk-$version-linux-$(uname -m).tar.gz
    tgz=$cache_dir/$tgz_name
    if [ ! -e "$tgz" ]; then
        if ! gh release download --dir "$cache_dir" --pattern "$tgz_name" "v$version"; then
            return
        fi
    fi

    # Install.
    mkdir -p "$root"
    tar -C "$root" -xf "$tgz"
}

if [ ! -f nuget.exe ]; then
    curl -o nuget.exe https://dist.nuget.org/win-x86-commandline/v4.9.4/nuget.exe
fi
${NUGET} >/dev/null

git submodule update --init --recursive

pushd runtime
git fetch
git cherry-pick --keep-redundant-commits 32670bdf9973  # https://github.com/dotnet/runtime/pull/70346
ln -fsT ../runtime-patches patches
quilt push -a
popd

pushd msbuild
need_msbuild=0
git fetch
# Enable building the net472 variant.
if ! git merge-base --is-ancestor ceed7cab7523 HEAD; then
    git cherry-pick ceed7cab7523
    # Do not set need_msbuild: if this is the only patch we need, then the
    # downloaded binaries are good enough.
fi
# https://github.com/dotnet/msbuild/pull/7731
if git merge-base --is-ancestor 67deba37040a HEAD && \
        ! git merge-base --is-ancestor 486a4599f4a5 HEAD; then
    git cherry-pick 486a4599f4a5
    need_msbuild=1
fi
if [ "$need_msbuild" -eq 0 ]; then
    touch .skip-build
    touch .skip-package
fi
popd

pushd roslyn
need_roslyn=0
# https://github.com/dotnet/roslyn/pull/57003
if ! git merge-base --is-ancestor d6eeb64a0191 HEAD; then
    git cherry-pick d6eeb64a0191
    need_roslyn=1
fi
if [ "$need_roslyn" -eq 0 ]; then
    touch .skip-build
    touch .skip-package
fi
popd

pushd sdk
update_nuget_config
popd

pushd installer
update_nuget_config
popd

install_host_sdk runtime
install_host_sdk msbuild
install_host_sdk roslyn
install_host_sdk sdk
install_host_sdk aspnetcore
