#!/bin/bash
# shellcheck disable=SC2154
set -e -u -x -o pipefail
shopt -s extglob
pushd "$(dirname "$0")"
# shellcheck disable=SC1091
. dotnet-versions
popd

ARCH=${ARCH:-s390x}
case "$ARCH on $(uname -m)" in
"ppc64le on ppc64le" | "s390x on s390x" | "x64 on x86_64")
    CROSS=false
    ;;
*)
    CROSS=true
    ;;
esac

BASEDIR=$(pwd)
DOTNET_DIR="$BASEDIR/dotnet"
USE_CUSTOM_PACKAGES=false
USE_CUSTOM_SDK=false
RUN_PREP=true
OUTPUT_DIR=$BASEDIR/output
PACKAGES_DIR=$BASEDIR/local-packages
DOWNLOAD_DIR=$BASEDIR/local-downloads

mkdir -p "$OUTPUT_DIR"
mkdir -p "$PACKAGES_DIR"
mkdir -p "$DOWNLOAD_DIR"

while [[ $# -gt 0 ]]; do
    case "$1" in
    --with-packages)
        USE_CUSTOM_PACKAGES=true
        CUSTOM_PACKAGES_DIR="$(cd "$2" && pwd)"
        if [ ! -d "$CUSTOM_PACKAGES_DIR" ]; then
            echo "Custom previously built packages directory '$CUSTOM_PACKAGES_DIR' does not exist"
            exit 1
        fi
        shift 2
        ;;
    --with-sdk)
        USE_CUSTOM_SDK=true
        SDK_TAR_PATH="$(cd "$(dirname "$2")" && pwd)/$(basename "$2")"
        shift 2
        ;;
    --no-prep)
        RUN_PREP=false
        shift
        ;;
    *)
        echo "Unknown argument: $1"
        exit 1
        ;;
    esac
done

build_sdk() {
    local sdk_build_flags=(
        --source-only
        --configuration Release
        --use-mono-runtime
        --source-repository "https://github.com/dotnet/dotnet"
        --source-version "$(git -C "$DOTNET_DIR" rev-parse HEAD)"
        -p:PortableBuild=true
        -p:UseSystemLibs=all
    )
    if "$CROSS"; then
        sdk_build_flags+=(
            --rid "linux-${ARCH}"
            --arch "$ARCH"
        )
    fi
    if [[ -z "${OFFICIAL_BUILD_ID:-}" ]]; then
        pushd dotnet
        if git merge-base --is-ancestor 44525024595742ebe09023abe709df51de65009b HEAD; then
            sdk_build_flags+=(--branding release)
        else
            sdk_build_flags+=(--branding rtm)
        fi
        popd
    fi

    if [[ -n "${OFFICIAL_BUILD_ID:-}" ]]; then
        sdk_build_flags+=(-p:OfficialBuildId="$OFFICIAL_BUILD_ID")
    fi

    if [[ "$USE_CUSTOM_PACKAGES" == true ]]; then
        sdk_build_flags+=(--with-packages "$CUSTOM_PACKAGES_DIR")
    fi

    if [[ "$USE_CUSTOM_SDK" == true ]]; then
        SDK_DIR="$BASEDIR/.bootstrap-sdk"
        if [[ ! -x "$SDK_DIR/dotnet" ]]; then
            echo "Extracting bootstrap SDK..."
            rm -rf "$SDK_DIR"
            mkdir -p "$SDK_DIR"
            tar -xzf "$SDK_TAR_PATH" -C "$SDK_DIR"
        fi
        sdk_build_flags+=(--with-sdk "$SDK_DIR")
    fi

    if [[ "$RUN_PREP" == true && "$USE_CUSTOM_SDK" == false ]]; then
        pushd "$DOTNET_DIR"
        ROOTFS_DIR=$(pwd) ./prep-source-build.sh
        popd
    fi
    pushd "$DOTNET_DIR"
    mv .git .git.bak
    ROOTFS_DIR=/ ./build.sh "${sdk_build_flags[@]}"
    mv .git .git.dir.bak
    mv .git.bak .git
    cp ./artifacts/assets/Release/Runtime/*/dotnet-runtime-"$runtime_version"-linux-"$ARCH".tar.gz "$OUTPUT_DIR"
    cp ./artifacts/assets/Release/Sdk/*/dotnet-sdk-"$sdk_version"-linux-"$ARCH".tar.gz "$OUTPUT_DIR"
    cp ./artifacts/packages/Release/Shipping/runtime/Microsoft.NETCore.App.Host.linux-"$ARCH"."$runtime_version".nupkg "$OUTPUT_DIR"
    cp ./artifacts/packages/Release/Shipping/runtime/Microsoft.NETCore.App.Runtime.linux-"$ARCH"."$runtime_version".nupkg "$OUTPUT_DIR"
    cp ./artifacts/packages/Release/Shipping/runtime/runtime.linux-"$ARCH".Microsoft.NETCore.ILDAsm."$runtime_version".nupkg "$OUTPUT_DIR"
    cp ./artifacts/packages/Release/Shipping/runtime/runtime.linux-"$ARCH".Microsoft.NETCore.ILDAsm."$runtime_version".nupkg "$OUTPUT_DIR"
    cp ./artifacts/packages/Release/Shipping/aspnetcore/Microsoft.AspNetCore.App.Runtime.linux-"$ARCH"."$runtime_version".nupkg "$OUTPUT_DIR"
    cp ./artifacts/assets/Release/Private.SourceBuilt.Artifacts."$sdk_version"*.linux-"$ARCH".tar.gz "$DOWNLOAD_DIR"
    cp ./prereqs/packages/archive/Private.SourceBuilt.Artifacts.Bootstrap.tar.gz "$PACKAGES_DIR"
    popd
}

projects=(sdk)
for project in "${projects[@]}"; do
    eval "build_${project}"
done
