#!/bin/bash
set -e -u -x

BASEDIR=$(pwd)
NUGET="mono ${BASEDIR}/nuget.exe"
PACKAGESDIR=${BASEDIR}/local-packages

function update_nuget_config {
    gawk -f - -i inplace NuGet.config <<EOF
    { print }
    /<packageSources>/ { Src = 1 }
    /<\/packageSources>/ { Src = 0 }
    /<clear \/>/ { if (Src) print "    <add key=\"local\" value=\"${PACKAGESDIR}\" />" }
EOF
}

if [ ! -f nuget.exe ]; then
	curl -o nuget.exe https://dist.nuget.org/win-x86-commandline/v4.9.4/nuget.exe
fi
${NUGET} >/dev/null

git submodule update --init --recursive

pushd runtime
git fetch https://github.com/iii-i/runtime.git 68266
git cherry-pick --allow-empty FETCH_HEAD
popd

pushd msbuild
git cherry-pick --allow-empty 486a4599f4a5  # https://github.com/dotnet/msbuild/pull/7731
popd

pushd sdk
update_nuget_config
popd

pushd installer
update_nuget_config
popd
