#!/bin/bash
set -e -u -x
cd "$(dirname "$0")"
sudo cp dotnet-daily@.service dotnet-daily@.timer /etc/systemd/system/
sudo systemctl daemon-reload
sudo systemctl enable --now dotnet-daily@"$USER".timer
