#!/bin/bash
set -e -u -x

BASEDIR=$(pwd)
PACKAGESDIR=${BASEDIR}/local-packages

function update_nuget_config {
    gawk -f - -i inplace NuGet.config <<EOF
    { print }
    /<packageSources>/ { Src = 1 }
    /<\/packageSources>/ { Src = 0 }
    /<clear \/>/ { if (Src) print "    <add key=\"local\" value=\"${PACKAGESDIR}\" />" }
EOF
}

function install_host_sdk {
    # Already installed?
    root=$1/.dotnet
    if [ -d "$root" ]; then return; fi

    # Installer available?
    version=$(jq -r .tools.dotnet "$1/global.json")
    cache_dir=$HOME/.dotnet
    tgz_name=dotnet-sdk-$version-linux-$(uname -m).tar.gz
    tgz=$cache_dir/$tgz_name
    if [ ! -e "$tgz" ]; then
        if ! gh release download --dir "$cache_dir" --pattern "$tgz_name" "v$version"; then
            return
        fi
    fi

    # Install.
    mkdir -p "$root"
    tar -C "$root" -xf "$tgz"
}

git submodule update --init --recursive

pushd runtime
git fetch
# https://github.com/dotnet/runtime/pull/70346
if ! git merge-base --is-ancestor 32670bdf9973 HEAD; then
    git cherry-pick 32670bdf9973
fi
# https://github.com/dotnet/runtime/pull/70901
if git merge-base --is-ancestor 7d562f9d2a42 HEAD && \
        ! git merge-base --is-ancestor 2a38e2093ab2 HEAD; then
    git cherry-pick 2a38e2093ab2
fi
# https://github.com/dotnet/runtime/pull/72049
if git merge-base --is-ancestor 0e800a6139f1 HEAD && \
        ! git merge-base --is-ancestor eaf0bb292dfa HEAD; then
    git cherry-pick eaf0bb292dfa
fi
# https://github.com/dotnet/runtime/pull/82173
if git merge-base --is-ancestor f478cfe83eb5 HEAD && \
        ! git merge-base --is-ancestor 4e0ff826321d HEAD; then
    git cherry-pick 4e0ff826321d
fi
# https://github.com/dotnet/runtime/pull/82678
if ! git merge-base --is-ancestor 961418a93f7e HEAD; then
    git cherry-pick 961418a93f7e
fi
# https://github.com/dotnet/runtime/pull/85307
if git merge-base --is-ancestor 93b487ad8075 HEAD && \
       ! git merge-base --is-ancestor 5cea3d67b9b1 HEAD; then
    git cherry-pick 5cea3d67b9b1
fi
if [ -s ../runtime-patches/series ]; then
    rm -rf .pc
    ln -fsT ../runtime-patches patches
    quilt push -a
fi
popd

pushd msbuild
need_msbuild=0
git fetch
# Enable building the net472 variant.
if ! git merge-base --is-ancestor ceed7cab7523 HEAD; then
    git cherry-pick ceed7cab7523
    # Do not set need_msbuild: if this is the only patch we need, then the
    # downloaded binaries are good enough.
fi
# https://github.com/dotnet/msbuild/pull/7731
if git merge-base --is-ancestor 67deba37040a HEAD && \
        ! git merge-base --is-ancestor 486a4599f4a5 HEAD; then
    git cherry-pick 486a4599f4a5
    need_msbuild=1
fi
if [ "$need_msbuild" -eq 0 ]; then
    touch .skip-build
    touch .skip-package
fi
popd

pushd roslyn
need_roslyn=0
# https://github.com/dotnet/roslyn/pull/57003
if ! git merge-base --is-ancestor d6eeb64a0191 HEAD; then
    git cherry-pick d6eeb64a0191
    need_roslyn=1
fi
if [ "$need_roslyn" -eq 0 ]; then
    touch .skip-build
    touch .skip-package
fi
popd

pushd sdk
update_nuget_config
popd

pushd installer
update_nuget_config
if ! git merge-base --is-ancestor 5501c7f23811 HEAD; then
    git cherry-pick 5501c7f23811
fi
popd

install_host_sdk runtime
install_host_sdk msbuild
install_host_sdk roslyn
install_host_sdk sdk
install_host_sdk aspnetcore
