#!/bin/bash
set -e -u -x -o pipefail

filter=()
if git -C "$(dirname "$0")" fetch --filter=tree:0 >/dev/null 2>&1; then
    # shellcheck disable=SC2034
    filter=(--filter=tree:0)
fi

function backport {
    # Commit that introduced the bug, or an empty string.
    fixes=$1
    # Commit or patch that fixes the bug, optionally followed by backported or
    # conflicting commits.
    commitids=$2
    if [ -n "$fixes" ] && ! git merge-base --is-ancestor "$fixes" HEAD; then
        return
    fi
    for commitid in $commitids; do
        if [ -e "$commitid" ]; then
            continue
        fi
        if git merge-base --is-ancestor "$commitid" HEAD; then
            return
        fi
    done
    for commitid in $commitids; do
        if [ -e "$commitid" ]; then
            git am "$commitid"
        else
            git cherry-pick "$commitid"
        fi
        break
    done
}

function prepare_sdk {
    pushd dotnet
    if [[ -s ../dotnet-patches/series ]] &&
        ! git merge-base --is-ancestor "49278fa" HEAD; then
        rm -rf .pc
        ln -fsT ../dotnet-patches patches
        quilt push -a
    else
        git fetch origin main
        backport "" e64f84d
    fi
    popd
}
projects=(dotnet)
git submodule update "${filter[@]}" --init --recursive -- "${projects[@]}"
eval prepare_sdk
