#!/bin/bash
set -e -u -x -o pipefail
basedir=$(cd "$(dirname "$0")"/.. && pwd)
mkdir -p "$basedir"/home/.nuget
mkdir -p "$basedir"/home/.local/share/NuGet
workdir=$(mktemp -d)
trap 'rm -r "$workdir"' EXIT
iidfile=$workdir/iid
ARCH=${ARCH-s390x}
deb_arch=$ARCH
gnu_arch=$ARCH
case "$deb_arch on $(uname -m)" in
"ppc64le on ppc64le" | "s390x on s390x" | "x64 on x86_64")
    deb_arch=
    ;;
"ppc64le on "*)
    deb_arch=ppc64el
    gnu_arch=powerpc64le
    ;;
esac
docker build --build-arg=deb_arch="$deb_arch" --build-arg=gnu_arch="$gnu_arch" --iidfile="$iidfile" "$basedir"/docker/image
iid=$(cat "$iidfile")
read -ra tty_arg < <([ ! -t 0 ] || echo --tty)
exec docker run \
    --env=ARCH="$ARCH" \
    --env=HOME="$HOME" \
    --init \
    --interactive \
    --rm \
    "${tty_arg[@]}" \
    --ulimit=nofile=16384 \
    --volume="$basedir:$basedir:z" \
    --volume="$HOME:$HOME:z" \
    --volume="$basedir/home/.nuget:$HOME/.nuget:z" \
    --volume="$basedir/home/.local/share/NuGet:$HOME/.local/share/NuGet:z" \
    --workdir="$basedir" \
    "$iid" \
    bash -c "groupadd -g $(id -g) $(id -ng) ; useradd -u $(id -u) -g $(id -g) $(id -nu) ; exec runuser -u $(id -nu) -- \"\$@\"" -- "$@"
