on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install packages
      run: sudo apt-get update && sudo apt-get install -y shellcheck shfmt
    - name: Lint
      run: ./lint
